### ISSUE TITLE
Storage System turning into Player Head

### ISSUE THREAD

**Issue by SavagePanda116** [SeanOMik/EnergeticStorage#10]
When I break an ES System, it doesn't stack with the ones that I get from /esgive, but it still functions as usual. However, when my players (non-op members) break an ES System, it turns into a Player Head. This Error appears in our console.

>.... [20:26:29 ERROR]: Could not pass event InventoryClickEvent to EnergeticStorage v0.4-SNAPSHOT
java.lang.NullPointerException: null
at net.seanomik.energeticstorage.gui.ESSystemGUI.initializeItems(ESSystemGUI.java:53) ~[?:?]
at net.seanomik.energeticstorage.gui.ESDriveGUI.onInventoryClick(ESDriveGUI.java:220) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor295.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-161]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-161]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-161]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-161]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2416) ~[patched_1.16.2.jar:git-Paper-161]
at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.2.jar:git-Paper-161]
at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.2.jar:git-Paper-161]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-161]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-161]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-161]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-161]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-161]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-161]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-161]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Paper-161]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.2.jar:git-Paper-161]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.2.jar:git-Paper-161]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-161]
at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by SeanOMik** [comment]
Hm, I'll take a look at it

**Comment by SeanOMik** [comment]
Those errors don't look related to breaking a system at all. And I can't reproduce your issue. Is there something else that may be triggering the errors?

**Comment by SavagePanda116** [comment]
So sorry, I took a few days off of server stuff!

I've done some more testing with it and I think the error is only happening when the player is using the Custom Enchantment called Telepathy that we have that is meant to add an item directly to the player's inventory. The enchant is broken and duplicating items so it's been disabled, but some players still have the enchant on their items even if it doesn't work.

But even without the enchant on their Pickaxe, sometimes when a player, including op players, breaks a system, it's name changes to "Player Head" instead of "ES System." It looks like it's happening when it is placed on a wall instead of a surface.

The few players that I have testing this are also now telling me that their items keep disappearing out of their drive when they try to remove them :(. 

We are also unable to use the "Trust Player" feature at all. Clicking on the green cement doesn't do anything.

**Comment by SeanOMik** [comment]
I'll take a look at that wall thing, also having enchants on things, and the trust player feature. The weird thing is items disappearing. Does this happen when they are clicking on items in the terminal to take them out, but when they click on them they disappear? When exactly do the items disappear?

**Comment by SavagePanda116** [comment]
The enchant plugin we are using is Crazy Enchantments, if that helps.

I personally haven't had any items disappear, but the player that has been helping with testing, who I trust, says that it only happened twice. Once, he put in 128 bamboo and when he clicked on it to take it out, all of it disappeared. The next time it was andesite and he only lost a stack of it, not all of it. It was right when he clicked on it in the terminal.

I'm so sorry to add another thing, but I mentioned before that the auto-complete for the commands uses nicknames with the exact colour codes and if I try to use it, I get kicked from the server for using "illegal characters", so I have to type out the full username.

**Comment by SeanOMik** [comment]
Okay, I'll take a look at that nickname thing. I'll mess around with a bunch items in the terminal also.

**Comment by SeanOMik** [comment]
I think I fixed that illegal characters issue, the systems on walls, and maybe the trust player option. [Here's the download.](https://trash.ctdo.de/file/6e6d637c) Tell me how that version goes.

**Comment by SavagePanda116** [comment]
We've been testing it and it seems to be working really well now! The names, systems on walls, and trust are all fixed :D . The only thing is that one of our custom enchantments, called Blast (breaks a 3x3 radius) is still turning the systems into "Player Heads" but that's it :D

**Comment by SeanOMik** [comment]
Okay I'll take a look at the custom enchants stuff.

**Comment by SeanOMik** [comment]
School got really busy so I wasn't able to work on plugins but I found some extra time. I'm not able to reproduce your issue, maybe its something with your Java version? What version of Java are you running? You can find it out by running ```java -version``` in your console (cmd/terminal)

**Comment by SavagePanda116** [comment]
That command isn't working, but I know that I am using Java 11 and PaperSpigot build #161 on 1.16.3.

**Comment by SeanOMik** [comment]
PaperSpigot #161 spigot 1.16.2 and I can see that you were running 1.16.2 from the error log above, but I tried #161 and #207 with Java 11, and I didn't encounter the issue. 

Does this happen with other items that store nbt, like enchant books, vanilla enchanted items, etc? Also, does this happen every single time you break the system or occasionally, and does the system still work when the player places that "Player head" block?
