### ISSUE TITLE
Error when trying to remove drives

### ISSUE THREAD

**Issue by SavagePanda116** [SeanOMik/EnergeticStorage#12]
We are unable to remove drives from the system without breaking the system. Whenever trying to remove the drive, we receive this error:

>.... [15:44:38 ERROR]: Could not pass event InventoryClickEvent to EnergeticStorage v0.4.2-SNAPSHOT
java.lang.NullPointerException: ItemStack can't be null/Air!
at de.tr7zw.nbtapi.energeticstorage.NBTItem.<init>(NBTItem.java:42) ~[?:?]
at de.tr7zw.nbtapi.energeticstorage.NBTItem.<init>(NBTItem.java:28) ~[?:?]
at net.seanomik.energeticstorage.utils.Utils.isItemADrive(Utils.java:145) ~[?:?]
at net.seanomik.energeticstorage.gui.ESDriveGUI.onInventoryClick(ESDriveGUI.java:222) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor338.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-194]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-194]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-194]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-194]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2427) ~[patched_1.16.3.jar:git-Paper-194]
at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.3.jar:git-Paper-194]
at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.3.jar:git-Paper-194]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-194]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-194]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-194]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-194]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-194]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-194]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-194]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.3.jar:git-Paper-194]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1264) ~[patched_1.16.3.jar:git-Paper-194]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-194]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-194]
at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by SeanOMik** [comment]
Hm, I'll take a look at that

**Comment by SeanOMik** [comment]
This might be fixed in [0.5.1-SNAPSHOT](https://github.com/SeanOMik/EnergeticStorage/releases/tag/0.5.1-SNAPSHOT).

**Comment by SeanOMik** [comment]
I'm guessing this was fixed since no response
