### ISSUE TITLE
Don't working in 1.17

### ISSUE THREAD

**Issue by DtnX** [SeanOMik/EnergeticStorage#22]
When I put the ES System on the ground the console gives me this error

[10:22:13] [Craft Scheduler Thread - 0/WARN]: [EnergeticStorage] Plugin EnergeticStorage v0.7.1-SNAPSHOT generated an exception while executing task 26
java.lang.NullPointerException: Cannot invoke "net.seanomik.energeticstorage.objects.ESSystem$SortOrder.toString()" because the return value of "net.seanomik.energeticstorage.objects.ESSystem.getSortOrder()" is null
        at net.seanomik.energeticstorage.files.PlayersFile.savePlayerSystem(PlayersFile.java:175) ~[?:?]
        at net.seanomik.energeticstorage.listeners.BlockPlaceListener.lambda$onBlockPlace$0(BlockPlaceListener.java:34) ~[?:?]
        at net.seanomik.energeticstorage.listeners.BlockPlaceListener$$Lambda$5427/0x000000003d6a6550.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:853) [?:?]

And when will I try to use

local chat: [10:25:00] [Render thread/INFO]: [CHAT] [Energetic Storage] This is an invalid ES System!

**Comment by SeanOMik** [comment]
I think I fixed it. Could you try to download [this jar](https://file.io/RIwYmJoUrbpK)?

**Comment by DtnX** [comment]
"The file you requested has been deleted" :/

**Comment by SeanOMik** [comment]
IDK why it says that, [here](https://drive.google.com/file/d/1qigqdnugaE7oKKHgG3KKyFDmeyl9Ooli/view?usp=sharing), I uploaded it to Google Drive.

**Comment by DtnX** [comment]
;-; 

[13:26:00] [Craft Scheduler Thread - 5/WARN]: [EnergeticStorage] Plugin EnergeticStorage v0.7.2-SNAPSHOT generated an exception while executing task 29
java.lang.NullPointerException: Cannot invoke "net.seanomik.energeticstorage.objects.ESSystem$SortOrder.toString()" because the return value of "net.seanomik.energeticstorage.objects.ESSystem.getSortOrder()" is null
        at net.seanomik.energeticstorage.files.PlayersFile.savePlayerSystem(PlayersFile.java:180) ~[?:?]
        at net.seanomik.energeticstorage.listeners.BlockPlaceListener.lambda$onBlockPlace$0(BlockPlaceListener.java:34) ~[?:?]
        at net.seanomik.energeticstorage.listeners.BlockPlaceListener$$Lambda$6477/0x00000000896b7510.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:853) [?:?]

**Comment by SeanOMik** [comment]
I was able to get it to happen on my PC and the [latest release](https://github.com/SeanOMik/EnergeticStorage/releases/tag/0.7.3-SNAPSHOT) fixed it for me.

**Comment by DtnX** [comment]
thank you very much, now it worked

**Comment by SeanOMik** [comment]
Awesome, glad to hear!
