### ISSUE TITLE
Error in Console [Bug] 

### ISSUE THREAD

**Issue by Ronnie0982** [SeanOMik/EnergeticStorage#26]
**Describe the bug**
Dunno what is wrong just seen it in the console

**Errors**
Plugin EnergeticStorage v0.7.3-SNAPSHOT generated an exception while executing task 35017
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because the return value of "net.seanomik.energeticstorage.files.PlayersFile.getConfigurationSection(String)" is null
        at net.seanomik.energeticstorage.files.PlayersFile.removePlayerSystem(PlayersFile.java:224) ~[?:?]
        at net.seanomik.energeticstorage.listeners.BlockBreakListener.lambda$onBlockBreakListener$0(BlockBreakListener.java:43) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-116]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-116]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-116]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Versions**
MC: 1.17.1
Java: 16

**Comment by SeanOMik** [comment]
It looks like this happened when you were destroying an ES System. Did you happen to clear the `players.yml` file before destroying the system?

**Comment by SeanOMik** [comment]
Closing due to inactivity
