### ISSUE TITLE
[Bug] Cant search

### ISSUE THREAD

**Issue by muckelba** [SeanOMik/EnergeticStorage#31]
**Describe the bug**
When ever i try to use the search function, a java exception is thrown and nothing happens ingame

**To Reproduce**
1. Search for an item

**Errors**
```
[20:54:13 ERROR]: Could not pass event InventoryClickEvent to EnergeticStorage v0.7.4-SNAPSHOT                                                                
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "list" is null                                                              
        at net.seanomik.energeticstorage.utils.Utils.listStringContainsString(Utils.java:125) ~[EnergeticStorage-v0.7.4-SNAPSHOT.jar:?]                       
        at net.seanomik.energeticstorage.gui.ESTerminalGUI.lambda$onInventoryClick$6(ESTerminalGUI.java:327) ~[EnergeticStorage-v0.7.4-SNAPSHOT.jar:?]        
        at net.seanomik.energeticstorage.anvilgui.AnvilGUI$ListenUp.onInventoryClick(AnvilGUI.java:250) ~[EnergeticStorage-v0.7.4-SNAPSHOT.jar:?]             
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-77]                         
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]                                 
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]                              
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2817) ~[?:?]                      
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]                         
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]                         
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]                                          
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-77]                                                               
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]                                                         
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]                                        
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-77]                                         
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-77]                                                  
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]                                                          
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-77]                                  
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-77]                                          
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]                                                      
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-77]                                 
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-77]                                         
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-77]                                      
        at java.lang.Thread.run(Thread.java:833) ~[?:?]  
```

**Versions**
MC: 1.18.1
Java: 17.0.1
PaperMC: paper-1.18.1-77

**Comment by SeanOMik** [comment]
Does this happen when you click the search button to open the search GUI, or after you've typed in what you want to search and attempt to do the search?

**Comment by SeanOMik** [comment]
Was able to reproduce, fixed it in the latest commit. Will make a release soon.
