### ISSUE TITLE
[Bug] Spamming error on console (spigot 1.16.5 -ES 0.7.4)

### ISSUE THREAD

**Issue by TheExotik** [SeanOMik/EnergeticStorage#36]
I don't know why, but after like 5 minutes server open/run, start spamming this error on console:
[07:16:37] [Server thread/ERROR]: Could not pass event WorldSaveEvent to EnergeticStorage v0.7.4-SNAPSHOT
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.WorldServer.save(WorldServer.java:866) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.saveChunks(MinecraftServer.java:794) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1147) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:966) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]
Caused by: java.lang.NullPointerException
        at net.seanomik.energeticstorage.utils.Utils.convertLocationToString(Utils.java:25) ~[?:?]
        at net.seanomik.energeticstorage.files.PlayersFile.savePlayerSystem(PlayersFile.java:178) ~[?:?]
        at net.seanomik.energeticstorage.files.PlayersFile.savePlayerSystems(PlayersFile.java:234) ~[?:?]
        at net.seanomik.energeticstorage.EnergeticStorage.savePlayerSystems(EnergeticStorage.java:70) ~[?:?]
        at net.seanomik.energeticstorage.EnergeticStorage.onWorldSaveEvent(EnergeticStorage.java:77) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        ... 9 more
        if someone know how fix it i'll loved.

**Comment by SeanOMik** [comment]
Closing due to inactivity
