### ISSUE TITLE
nbtapi error during load

### ISSUE THREAD

**Issue by FamousL** [SeanOMik/EnergeticStorage#46]
Hello,  I think I am doing something wrong here, but loading up the spigotmc.org plugin failed with multiple errors, attempting to compile the plugin required a slight update to the pom to use apache shade dependency to 3.3.1 (3.3.0 is missing from apache's repos) However now during load I am seeing this issue:

[11:06:38] [Server thread/ERROR]: Error occurred while enabling EnergeticStorage v0.7.6-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: de/tr7zw/changeme/nbtapi/NBTItem
        at net.seanomik.energeticstorage.utils.ItemConstructor.createSystemBlock(ItemConstructor.java:23) ~[energeticstorage-0.7.6-SNAPSHOT.jar:?]
        at net.seanomik.energeticstorage.utils.ItemRecipes.registerBlockRecipes(ItemRecipes.java:19) ~[energeticstorage-0.7.6-SNAPSHOT.jar:?]
        at net.seanomik.energeticstorage.utils.ItemRecipes.registerRecipes(ItemRecipes.java:12) ~[energeticstorage-0.7.6-SNAPSHOT.jar:?]
        at net.seanomik.energeticstorage.EnergeticStorage.onEnable(EnergeticStorage.java:33) ~[energeticstorage-0.7.6-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-341]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-341]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-341]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-341]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-341]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-341]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-341]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: de.tr7zw.changeme.nbtapi.NBTItem
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 15 more

**Comment by FamousL** [comment]
additional information from the build itself I had this logged:

INFO] --- maven-shade-plugin:3.3.1-SNAPSHOT:shade (shade) @ energeticstorage ---
[INFO] Including com.google.guava:guava:jar:21.0 in the shaded jar.
[INFO] Including com.google.code.gson:gson:jar:2.8.0 in the shaded jar.
[INFO] Including de.tr7zw:item-nbt-api:jar:2.9.2-SNAPSHOT in the shaded jar.
[INFO] Including de.tr7zw:functional-annotations:jar:0.1-SNAPSHOT in the shaded jar.
[INFO] Including net.wesjd:anvilgui:jar:1.5.3-SNAPSHOT in the shaded jar.
[INFO] Including com.googlecode.json-simple:json-simple:jar:1.1.1 in the shaded jar.
[INFO] Including junit:junit:jar:4.10 in the shaded jar.
[INFO] Including org.hamcrest:hamcrest-core:jar:1.1 in the shaded jar.
[INFO] Including org.apache.commons:commons-text:jar:1.9 in the shaded jar.
[INFO] Including org.apache.commons:commons-lang3:jar:3.11 in the shaded jar.
[INFO] Including org.jetbrains:annotations:jar:13.0 in the shaded jar.
[INFO] Including com.mojang:authlib:jar:1.5.21 in the shaded jar.
[INFO] Including org.apache.logging.log4j:log4j-core:jar:2.0-beta9 in the shaded jar.
[INFO] Including commons-codec:commons-codec:jar:1.9 in the shaded jar.
[INFO] Including org.apache.logging.log4j:log4j-api:jar:2.0-beta9 in the shaded jar.
[INFO] Including com.google.code.findbugs:jsr305:jar:2.0.1 in the shaded jar.
[INFO] Including commons-io:commons-io:jar:2.4 in the shaded jar.
[INFO] Including org.bstats:bstats-bukkit:jar:2.2.1 in the shaded jar.
[INFO] Including org.bstats:bstats-base:jar:2.2.1 in the shaded jar.
[INFO] Dependency-reduced POM written at: /home/minecraft/build/EnergeticStorage/dependency-reduced-pom.xml
