### ISSUE TITLE
1.16.1 Support?

### ISSUE THREAD

**Issue by Fundryi** [SeanOMik/EnergeticStorage#5]
Im on the latest PaperSpigot 1.16.1.

Whenever I type /esgive system I get the error below: (the crafting recipe does also not work for me [Link](https://i.imgur.com/BDVWK5Y.png))

```
.... [09:28:41 INFO]: Fundryi issued server command: /esgive system
>.... [09:28:41 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'esgive' in plugin EnergeticStorage v0.2-SNAPSHOT
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-92]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-92]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-92]
at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1912) ~[patched_1.16.1.jar:git-Paper-92]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1723) ~[patched_1.16.1.jar:git-Paper-92]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-92]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-92]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-92]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-92]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-92]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-92]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-92]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-92]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-92]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-92]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-92]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-92]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-92]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: de.tr7zw.nbtapi.NbtApiException: Method not loaded! 'ITEMSTACK_NMSCOPY'
at de.tr7zw.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:149) ~[?:?]
at de.tr7zw.nbtapi.NBTItem.getCompound(NBTItem.java:34) ~[?:?]
at de.tr7zw.nbtapi.NBTReflectionUtil.setData(NBTReflectionUtil.java:503) ~[?:?]
at de.tr7zw.nbtapi.NBTCompound.setBoolean(NBTCompound.java:270) ~[?:?]
at net.seanomik.energeticstorage.utils.ItemConstructor.createSystemBlock(ItemConstructor.java:24) ~[?:?]
at net.seanomik.energeticstorage.commands.ESGiveCommand.onCommand(ESGiveCommand.java:97) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-92]
... 18 more
```

I guess you just haven't got around to update it to 1.16.1, but it would be cool if you could support it!

Regards

**Comment by SeanOMik** [comment]
The plugin doesn't yet support 1.16 but I'm gonna work on it tonight. It should be pretty easy to get working.

Thanks for the pull request.

**Comment by SeanOMik** [comment]
I just created a new release that supports 1.16. [Enjoy!](https://github.com/SeanOMik/EnergeticStorage/releases/tag/0.3-SNAPSHOT)
